version: '3.8'
services:
  webserver:
    build:
      context: ./webserver/app/
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app_network
  predictor:
    build:
      context: ./predictor/app/
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app_network
networks:
  app_network:
    driver: bridge