apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\pspez\Documents\Progetti\VNCCProject\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: inserter
  name: inserter
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    io.kompose.service: inserter
status:
  loadBalancer: {}
