apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: predictor
  name: predictor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: predictor
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: predictor
    spec:
      containers:
        - image: predictor
          name: predictor
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          resources: {}
          volumeMounts:
            - mountPath: /app/data
              name: model-data
      restartPolicy: Always
      volumes:
        - name: model-data
          persistentVolumeClaim:
            claimName: model-data
status: {}
