apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\pspez\Documents\Progetti\VNCCProject\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: training
  name: training
spec:
  ports:
    - name: "3002"
      port: 3002
      targetPort: 3002
  selector:
    io.kompose.service: training
status:
  loadBalancer: {}
