apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: training
  name: training
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: training
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: training
    spec:
      containers:
        - image: training
          name: training
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          resources: {}
          volumeMounts:
            - mountPath: /app/data
              name: model-data
      restartPolicy: Always
      volumes:
        - name: model-data
          persistentVolumeClaim:
            claimName: model-data
status: {}
