apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\pspez\Documents\Progetti\VNCCProject\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: training
  name: training
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: training
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\pspez\Documents\Progetti\VNCCProject\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: training
    spec:
      containers:
        - image: training
          name: training
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          resources: {}
          volumeMounts:
            - mountPath: /app/data
              name: model-data
      restartPolicy: Always
      volumes:
        - name: model-data
          persistentVolumeClaim:
            claimName: model-data
status: {}
