apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: inserter
  name: inserter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: inserter
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: inserter
    spec:
      containers:
        - image: inserter
          name: inserter
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          resources: {}
      restartPolicy: Always
status: {}
